import { chromium } from 'playwright';
const OUT = process.argv[2] as string;
const wait = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const ctx = await browser.newContext({ viewport: { width: 393, height: 852 }, deviceScaleFactor: 3, isMobile: true, hasTouch: true });
const page = await ctx.newPage();
const cdp = await ctx.newCDPSession(page);
const touch = async (x: number, y: number): Promise<void> => { await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y, id: 1 }] }); await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); };
const center = async (sel: string): Promise<{ x: number; y: number } | null> => (await page.evaluate(`(() => { const e = document.querySelector(${JSON.stringify(sel)}); if (!e) return null; const r = e.getBoundingClientRect(); return { x: r.left + r.width / 2, y: r.top + r.height / 2 }; })()`)) as { x: number; y: number } | null;
const tap = async (sel: string): Promise<boolean> => { const c = await center(sel); if (!c) { console.log('no', sel); return false; } await touch(c.x, c.y); await wait(350); return true; };
const shot = async (name: string): Promise<void> => { await page.screenshot({ path: `${OUT}/${name}.png` }); console.log('shot', name); };
const errs: string[] = []; page.on('pageerror', (e) => errs.push(String(e)));
await page.goto('http://100.114.231.15:5189/?debug=1&px=1&fresh=1&tut=0&celebrate=1', { waitUntil: 'load' });
await page.waitForFunction('!!window.__pj', null, { timeout: 20000 });
await wait(600);
await page.evaluate(`window.__pj.skip(700)`); await wait(400);
await shot('s1-home-guests');
await tap('#hud-menu'); await shot('s2-menu'); await tap('#hud-menu');
await tap('#hud-right [data-cell="build"]'); await shot('s3-build'); await tap('#win-build .kwin-close');
await tap('#hud-right [data-cell="sns"]'); await shot('s4-sns-timeline');
await tap('#win-sns .ktab[data-tab="messages"], #win-sns [data-tab="messages"]'); await shot('s5-sns-messages');
await tap('#win-sns .ktab[data-tab="friends"], #win-sns [data-tab="friends"]'); await shot('s6-sns-friends'); await tap('#win-sns .kwin-close');
await page.evaluate(`window.__pj.certWin.show()`); await wait(300); await shot('s7-cert'); await tap('#win-cert .kwin-close');
await tap('#hud-right [data-cell="shop"]'); await shot('s8-shop'); await tap('#win-shop .kwin-close');
await page.evaluate(`window.__pj.investWin.show()`); await wait(300); await shot('s9-invest'); await tap('#win-invest .kwin-close');
const pool = (await page.evaluate(`(() => { const w = window.__pj; const p = w.game.pools.all[0]; w.poolInfo.show(p.id); return p.id; })()`)) as number;
await wait(300); await shot('s10-pool-info'); await tap('#win-pool .kwin-close');
await page.evaluate(`(() => { const w = window.__pj; const g = w.guests ? null : w.game.guests.all[0]; if (g) w.guestInfo.show(g); })()`); await wait(300); await shot('s11-guest-info');
const gi = await page.evaluate(`!document.getElementById('win-guest').hidden`); if (gi) await tap('#win-guest .kwin-close');
// 폐장까지 감아 결산
await page.evaluate(`(() => { const w = window.__pj; w.resultsCtl.enabled = true; w.skip(w.TPD - w.game.tick + 2); })()`); await wait(900);
await shot('s12-day-end');
console.log('pageerrors', JSON.stringify(errs), 'pool', pool);
await browser.close();
