import {describe,it,expect} from 'vitest';
import {Game,FACILITY_DEFS} from '../../sim/game.js';
import {BUILD_TABS,currentBuildCatalog} from './build.js';
const stages=['stage_river_lv1','stage_river_lv2','stage_river_lv3'];
function place(g:Game,id:string,facing:0|1){for(let j=0;j<g.grid.h;j++)for(let i=0;i<g.grid.w;i++){const r=g.placeFacility(id,i,j,facing);if(r.ok)return r.uid!;}throw Error('No site '+id);}
describe('approved outdoor catalog preserves the previous game',()=>{
 it('offers all seven accepted assets in intended tabs, retires only legacy construction',()=>{const catalog=currentBuildCatalog([...FACILITY_DEFS.values()]);for(const [id,tab] of Object.entries({playground:'play',bungee_jump:'play',stage_river_lv1:'play',stage_river_lv2:'play',stage_river_lv3:'play',photozone:'decor',pavilion:'seat'})){expect(catalog.some(d=>d.id===id),id).toBe(true);expect(BUILD_TABS.filter(t=>t.match(FACILITY_DEFS.get(id)!)).map(t=>t.id)).toEqual([tab]);}expect(catalog.some(d=>d.id==='stage_river')).toBe(false);expect(catalog.some(d=>d.id==='mongol_tent')).toBe(false);expect(stages.map(id=>{const d=FACILITY_DEFS.get(id)!;return[d.w,d.d];})).toEqual([[4,3],[5,4],[6,5]]);});
 it('new stage construction and save reload do not enlarge legacy placed stage or terrain',()=>{const base=new Game(2);base.money=1e7;base.openLand(5);const snapshot=base.toSnapshot();for(const facing of [0,1] as const){const g=Game.fromSnapshot(snapshot);g.unlocked.facilities.add('stage_river');const old=place(g,'stage_river',facing),before={...g.facilities.byUid(old)!},floor=[...g.grid.floor],levels=[...g.grid.levels];for(const id of stages){expect(g.isUnlocked(id)).toBe(true);place(g,id,facing);}const restored=Game.fromSnapshot(g.toSnapshot());expect(restored.facilities.byUid(old)).toEqual(before);expect([...restored.grid.floor]).toEqual(floor);expect([...restored.grid.levels]).toEqual(levels);for(const id of stages)expect(restored.facilities.all.some(f=>f.defId===id)).toBe(true);}const legacy=FACILITY_DEFS.get('stage_river')!;expect([legacy.w,legacy.d,legacy.capacity,legacy.class]).toEqual([3,2,0,'decor']);});
});
